export const SIGN_IN_REQUEST = 'AUTH::SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'AUTH::SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'AUTH::SIGN_IN_FAILURE'
export const SIGN_IN_LOADING = 'AUTH::SIGN_IN_LOADING'

export const FETCH_USER_DATA = 'AUTH::FETCH_USER_DATA'
export const SET_CURRENT_USER_DATA = 'AUTH::SET_CURRENT_USER_DATA'

export const CURRENT_USER_REQUEST = 'AUTH::CURRENT_USER_REQUEST'
export const CURRENT_USER_SUCCESS = 'AUTH::CURRENT_USER_SUCCESS'

export const SIGN_UP_REQUEST = 'AUTH::SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'AUTH::SIGN_UP_SUCCESS'

export const LOGOUT = 'AUTH::LOGOUT'
